Controllers/AuthenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ProjectAdmin.Objects;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using ProjectAdmin.Models;
using ProjectAdmin.CustomAttributes;
using ProjectAdmin.Interfaces;
using ProjectAdmin.Utilities;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;

namespace ProjectAdmin.Controllers
{
    [AllowAnonymous]
    public class AuthenController : BaseController<AuthenController>
    {

        private readonly IAuthenService _authenService;
        private readonly IAccountService _accountService;

        public AuthenController(IAuthenService authenService, IAccountService accountService)
        {
            _authenService = authenService;
            _accountService = accountService;
        }

        //[Route("/login")]
        public IActionResult Login()
        {
            var model = new LoginModel();
            return View(model);
        }
        public IActionResult ForgotPassword()
        {
            var model = new LoginModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture ?? "")),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
        public IActionResult Gets()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {

            if (ModelState.IsValid)
            {
                var header = Header;
                header.Action = CustomConfigApi.Account.Login;
                var request = new LoginRequest
                {
                    passStr = model.passStr,
                    userStr = model.userStr,
                    transferKeyStr = "web"
                };

                var obj = _authenService.Login(header, request);
                if (obj != null && obj.data != null && obj.error.code == 0)
                {
                    var claims = new List<Claim>
                    {
                        //new Claim(ClaimTypes.Name, obj.data.staff.account.username),
                        new Claim(Constants.FULL_NAME, obj.data.user.username),
                        //new Claim(Constants.USER_ROLE, obj.data.staff.account.role.name),
                        //new Claim(Constants.USER_POSITION, obj.data.staff.companyTree.osType),
                        new Claim(Constants.TOKEN, obj.data.token.key),
                        new Claim(Constants.TTL, obj.data.token.timeDestroy.ToString()),
                        new Claim(Constants.USER_ROLE, obj.data.user.role_id.ToString()),
                        //new Claim(Constants.USER_AVATAR,CustomConfigApi.ImageDomain + obj.data.staff.avatarPath),
                        //new Claim(Constants.USER_MENUS, Get_Menus(obj.data.token).Count > 0 ? JsonConvert.SerializeObject(Get_Menus(obj.data.token)) : ""),
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(
                        scheme: CookieAuthenticationDefaults.AuthenticationScheme,
                        principal: new ClaimsPrincipal(claimsIdentity),
                        properties: new AuthenticationProperties
                        {
                            IsPersistent = true,
                        }).ConfigureAwait(false);
                    if (obj.data.user.role_id == 4)
                    {
                        return RedirectToAction("Index", "ProfitReport");
                    }
                    if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    

                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }

                }
                else
                {
                    if (model.userStr == null)
                    {
                        var username = model.language == null ? "Bạn chưa nhập tên đăng nhập" : "This is a required field";
                        ModelState.AddModelError("userStr", username);
                    }
                    if (model.passStr == null)
                    {
                        var passStr = model.language == null ? "Bạn chưa nhập mật khẩu" : "This is a required field";
                        ModelState.AddModelError("passStr", passStr);
                    }
                    else if (model.passStr.Length <= 6)
                    {
                        var passStrLength = model.language == null ? "Mật khẩu phải từ 6 ký tự trở lên" : "Password must be 6 or more characters";
                        ModelState.AddModelError("passStr", passStrLength);
                    }

                    var html = model.language == null ? "Thông tin đăng nhập không chính xác" : "Login information is incorrect!";
                    ModelState.AddModelError("", html);
                }
            }
            return View(model);
        }


        public async Task<IActionResult> Logout()
        {
            var logout = await LogoutAsync();
            if (logout)
            {
                return RedirectToAction("login", "authen");
            }
            else
            {
                await HttpContext.SignOutAsync().ConfigureAwait(false);
                return RedirectToAction("login", "authen");
            }
            /*
            var header = Header;

            header.Action = CustomConfigApi.Account.Logout;            

            var obj = _authenService.Logout(header);
            if (obj != null && obj.error == 0)
            {
                await HttpContext.SignOutAsync().ConfigureAwait(false);
                return RedirectToAction("login", "authen");
            }
            return RedirectToAction("error","home");
            */
        }

        [HttpPost]
        public async Task<IActionResult> LogoutAjax()
        {
            var logout = await LogoutAsync();
            if (logout)
            {
                return Ok();
            }
            else
            {
                return NotFound();
            }
            /*
            var header = Header;

            header.Action = CustomConfigApi.Account.Logout;            

            var obj = _authenService.Logout(header);
            if (obj != null && obj.error == 0)
            {
                await HttpContext.SignOutAsync().ConfigureAwait(false);
                return RedirectToAction("login", "authen");
            }
            return RedirectToAction("error","home");
            */
        }

        private async Task<bool> LogoutAsync()
        {
            var header = Header;
            header.Action = CustomConfigApi.Account.Logout;
            var request = new LogoutRequest
            {
                tokenStr = header.Authorization,

            };
            var obj = _authenService.Logout(header, request);
            if (obj != null && obj.error.code == 0)
            {
                await HttpContext.SignOutAsync().ConfigureAwait(false);
                return true;
            }
            return false;
        }

        private async Task<bool> RefreshTokenAsync()
        {
            var header = Header;
            header.Action = CustomConfigApi.Account.RefreshToken;

            var request = new RefreshTokenRequest
            {
                refresh_token = ProjectRefreshToken
            };

            var obj = _authenService.RefreshToken(header, request);

            if (obj != null && obj.error.code == 0)
            {
                var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, Username),
                        new Claim(Constants.TOKEN, obj.data.token.key),
                        new Claim(Constants.REFRESH_TOKEN, ProjectRefreshToken),
                    };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(
                    scheme: CookieAuthenticationDefaults.AuthenticationScheme,
                    principal: new ClaimsPrincipal(claimsIdentity),
                    properties: new AuthenticationProperties
                    {
                        IsPersistent = true,
                    }).ConfigureAwait(true);
                return true;
            }
            else
            {
                var logout = LogoutAsync();

                return false;
            }

        }

        [Route("authen/refresh")]
        public IActionResult RefreshToken(string currentUrl)
        {
            var refreshToken = RefreshTokenAsync();
            if (refreshToken.Result)
            {
                if (string.IsNullOrEmpty(currentUrl))
                {
                    return RedirectToPage("/home");
                }
                else
                {
                    return RedirectToPage(currentUrl);
                }
            }
            else
            {
                System.Diagnostics.Debug.WriteLine($"MainPort: {CustomConfigApi.MainPort}");
                return RedirectToPage("~/authen/login");
            }
        }

        [HttpPost]

Views/Authen/ChangePassword.cshtml
@*@{
        Layout = null;
        ViewData["Title"] = "Change Password";
    }

    <form method="post" id="form_Change_password" onsubmit="return false">
        <div class="content-model">
            <div class="row">
                <div class="form-group col-12">
                    <label class="mb-4"><strong>Current Password:</strong><span class="text-danger fw-bold ms-2">*</span></label>
                    <input type="password" class="form-control" name="password" />
                </div>
                <div class="form-group col-12 pt-3">
                    <label class="mb-4"><strong>New Password:</strong><span class="text-danger fw-bold ms-2">*</span></label>
                    <input type="password" class="form-control" name="newPassword" id="newPassword"/>
                </div>
                <div class="form-group col-12 pt-3">
                    <label class="mb-4"><strong>New Confirm Password:</strong><span class="text-danger fw-bold ms-2">*</span></label>
                    <input type="password" class="form-control"  name="newConfirmPassword"/>
                </div>

            </div>

            <input id="submit_handle" type="submit" style="display: none">
            <div style="display:flex;justify-content:center" class="pt-5">
                <button class="btn btn-sm recepits-btn-close" style="margin-right: 16px; background-color: aliceblue;">Hủy bỏ</button>
                <button type="button" class="btn btn-submit btn-icon-sm " id="btn-Change_password" style="background-color: #92D59C" >Áp dụng</button>
            </div>
        </div>
    </form>*@


@model ProjectAdmin.Models.LoginModel
@{
    ViewData["Title"] = "Đổi mật khẩu";
    ViewData["BodyClass"] = "authen_changePassword";
    Layout = null;
}

<div class="d-flex flex-column flex-root">
    <!--begin::Authentication - forgotPassword -->
    <div class="d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed" style="background-image: url(assets/media/illustrations/progress-hd.png)">
        <!--begin::Content-->
        <div class="d-flex flex-center flex-column flex-column-fluid pb-lg-20">
            <!--begin::Logo-->
            <!--end::Logo-->
            <!--begin::Wrapper-->
            <div class="w-100 authen_box" style="padding:20px 32px">
                <!--begin::Form-->
                <form class="form " id="authen_forgot_form" onsubmit="return false;">
                    <!--begin::Heading-->
                   
                  
                    <!--begin::Heading-->
                    <!--begin::Input group-->
                    <div class="form-group mb-6">
                        <label class="form-label text_label">
                            Old password
                        </label>
                        @*<input class="form-control ver_2" type="email" name="email" placeholder="Nhập mật khẩu mới" />*@
                        <div class="input-group ver_2 mb-2">
                            <input type="password" class="form-control showHidePassInput" id="passOldStr" name="passOldStr" autocomplete="off" placeholder="Enter your old password
">
                            <div class="input-group-apppend">
                                <i class="ri-eye-line" style="display:none;"></i>
                                <i class="ri-eye-off-line"></i>
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-6">
                        <label class="form-label text_label">
                            New password
                        </label>
                        @*<input class="form-control ver_2" type="email" name="email" placeholder="Nhập mật khẩu mới" />*@
                        <div class="input-group ver_2 mb-2">
                            <input type="password" class="form-control showHidePassInput" id="passNewStr" name="passNewStr" autocomplete="off" placeholder="Enter your new password
">
                            <div class="input-group-apppend">
                                <i class="ri-eye-line" style="display:none;"></i>
                                <i class="ri-eye-off-line"></i>
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-10">
                        <label class="form-label text_label">
                            Confirm password
                        </label>
                        @*<input class="form-control ver_2" type="email" name="email" placeholder="Nhập lại mật khẩu mới" />*@
                        <div class="input-group ver_2 mb-2">
                            <input type="password" class="form-control showHidePassInput" id="newConfirmPassword" name="newConfirmPassword" autocomplete="off" placeholder="Enter a new password">
                            <div class="input-group-apppend">
                                <i class="ri-eye-line" style="display:none;"></i>
                                <i class="ri-eye-off-line"></i>
                            </div>
                        </div>
                    </div>
                    <!--end::Input group-->
                    <!--begin::Actions-->
                    <div class="text-center" style="display:flex">
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger" style="width:100%"></div>
                        <!--begin::Submit button-->
                        <button type="button" class="btn btn-lg btn-success ver_2 w-100 recepits-btn-close" style="margin: 5px; background: #fff; color: black; border: 1px solid #EBEEF4; ">
                            <span class="indicator-label">
                                Close
                            </span>
                        </button>
                        <button type="submit" class="btn btn-lg btn-success ver_2 w-100" style="margin:5px">
                            <span class="indicator-label">
                                Reset Password
                            </span>
                            <span class="indicator-progress">
                                Please wait...
                                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                            </span>

                        </button>

                        <!--end::Submit button-->
                        <!--begin::Separator-->
                        <!--end::Google link-->
                    </div>
                    <!--end::Actions-->
                </form>
                <!--end::Form-->
            </div>
            <!--end::Wrapper-->
        </div>
        <!--end::Content-->
    </div>
    <!--end::Authentication - forgotPassword-->
</div>

Views/Authen/Login.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<CommonResources> SharedLocalizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@model ProjectAdmin.Models.LoginModel
@{
    ViewData["Title"] = "Đăng nhập";
    ViewData["BodyClass"] = "Login";
    Layout = "_AuthenLayout";
}


<div class="d-flex flex-column flex-root">

    <!--begin::Authentication - Sign-in -->
    <div class="d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed" style="background-image: url(assets/media/illustrations/progress-hd.png)">
        <!--begin::Content-->
        <div class="p-lg-12 p-md-8 p-4 d-flex justify-content-between">
            <img src="~/img/Logo (3).png" />
            @*<div id="is_menu_mobile" class="language-menu mb-4">
            <div class="col-12 col-md-12 row title-menu-2">
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle select-language-v2 w-100" style="border:none;color:white" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <img src="~/img/Language/GB.png" />&nbsp;&nbsp; English
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" style="background-color: #23262F">
                        <li>
                            <a style="text-decoration: none !important;" href="#" class="select-language" data-lang="en">
                                <img src="~/img/Language/GB.png" /> &nbsp;&nbsp; English
                            </a>
                        </li>

                        <li>
                            <a style="text-decoration: none !important;" href="#" class="select-language" data-lang="zh-CN">
                                <img src="~/img/Language/CN.png" /> &nbsp;&nbsp; Chinese
                            </a>
                        </li>

                        <li>
                            <a style="text-decoration: none !important;" href="#" class="select-language" data-lang="fr">

                                <img src="~/img/Language/FR.png" />&nbsp;&nbsp; French
                            </a>
                        </li>

                        <li>
                            <a style="text-decoration: none !important;" href="#" class="select-language" data-lang="ja">

                                <img src="~/img/Language/JP.png" />&nbsp;&nbsp; Japanese
                            </a>
                        </li>
                        <li>
                            <a style="text-decoration: none !important;" href="#" class="select-language" data-lang="ko">

                                <img src="~/img/Language/KR.png" />&nbsp;&nbsp; Korean

                            </a>
                        </li>
                        <li>
                            <a style="text-decoration: none !important;" href="#" class="select-language" data-lang="es">
                                <img src="~/img/Language/ES.png" />&nbsp;&nbsp; Spanish
                            </a>
                        </li>
                        <li>
                            <a style="text-decoration: none !important;" href="#" class="select-language" data-lang="vi">

                                <img src="~/img/Language/VN.png" />    &nbsp;&nbsp; Vietnamese
                            </a>
                        </li>
                        <li>
                            <a style="text-decoration: none !important;" href="#" class="select-language" data-lang="km">
                                <img src="~/img/Language/KH.png" />&nbsp;&nbsp; Cambodian
                            </a>
                        </li>
                        <li>
                            <a style="text-decoration: none !important;" href="#" class="select-language" data-lang="th">
                                <img src="~/img/Language/TH.png" />&nbsp;&nbsp; Thai
                            </a>
                        </li>
                    </ul>

                </div>



            </div>
        </div>*@
            @{ var requestCulture = Context.Features.Get<IRequestCultureFeature>();
                var cultureItems = LocOptions.Value.SupportedUICultures
                    .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
                    .ToList();
                var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
            }
            <form id="selectLanguage" asp-controller="Authen"
                  asp-action="SetLanguage" asp-route-returnUrl="@returnUrl"
                  method="post" class="form-horizontal" role="form">

                <select asp-for="@requestCulture.RequestCulture.UICulture.Name" name="culture" onchange="this.form.submit();"
                        asp-name="language-picker-select" id="language-picker-select" class="language-picker">
                    <option lang="vn" value="" data-thumbnail="/img/Language/VN.png"> Vietnamese</option>
                    <option lang="en" value="en-US" data-thumbnail="/img/Language/GB.png"> EngLish</option>
                </select>
            </form>
        </div>
        <div class="d-flex flex-center flex-column flex-column-fluid p-10 pb-lg-20">
            <!--begin::Logo-->
            <!--end::Logo-->
            <!--begin::Wrapper-->

            <div class="w-lg-450px mx-auto authen_box">
                <!--begin::Form-->
                <form class="form w-100" asp-action="Login" asp-controller="Authen" id="kt_sign_in_form">
                    <input name="language" class="language" id="language" hidden/>

                    <!--begin::Heading-->

                    <span style="margin-bottom: 4px;" class="text_1">
                        @SharedLocalizer["textLogin"].Value
                        @*@SharedLocalizer["abc"]*@
                    </span><br />
                    <span class="text_2">
                        @SharedLocalizer["textTitleLogin"].Value
                    </span><br />
                    <div class="text-center mb-10">
                        @*<div class="d-flex align-items-center justify-content-center">
                <img src="~/img/framer.png" />&nbsp;
                <span style="font-size:20px; font-weight:600">FTM Admin</span>
            </div>*@

                        <!--begin::Title-->
                        @*<h1 class="text-dark mb-3 text-uppercase" style="padding-top:15px;font-size:20px;line-height:28px">LogIn</h1>
            <h1 class="text-gray-400" style="padding-top:15px;font-size:14px">Welcome to the system Project. Login to use</h1>*@
                        <!--end::Title-->
                        <!--begin::Link-->
                        <!--end::Link-->
                    </div>
                    <!--begin::Heading-->
                    <!--begin::Input group-->
                    <div class="fv-row mb-10">
                        <!--begin::Label-->
                        <label class="form-label text_3">@SharedLocalizer["labelEmail"].Value</label>
                        <!--end::Label-->
                        <!--begin::Input-->
                        <input class="form-control ver_2" type="text" asp-for="userStr" placeholder="@SharedLocalizer["placeholderEmail"].Value" style="background-color:#23262F; color:#fff;" />
                        <span asp-validation-for="userStr" class="d-block invalid-feedback"></span>
                        <!--end::Input-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="fv-row mb-10">
                        <!--begin::Wrapper-->
                        <div class="d-flex flex-stack mb-2">
                            <!--begin::Label-->
                            <label class="form-label text_3">@SharedLocalizer["labelPassword"].Value</label>
                            <!--end::Label-->
                            <!--begin::Link-->
                            <!--end::Link-->
                        </div>
                        <!--end::Wrapper-->
                        <!--begin::Input-->
                        <div class="input-group ver_2 mb-2">

                            <input type="password" asp-for="passStr" class="form-control showHidePassInput" id="passStr" autocomplete="off" placeholder="@SharedLocalizer["placeholderPassword"].Value" style="background-color:#23262F; color:#fff;">
                            <div class="input-group-apppend" style="background-color:#23262F; color:#777E90;">
                                <i class="ri-eye-line" style="display:none;"></i>
                                <i class="ri-eye-off-line"></i>
                            </div>
                            @*<input class="form-control form-control-lg form-control-solid placeholder_1" type="password" asp-for="passStr" autocomplete="off" placeholder="Nhập mật khẩu đăng nhập" />*@
                        </div>
                        @*<input class="form-control form-control-lg form-control-solid placeholder_1" type="password" asp-for="passStr" autocomplete="off" placeholder="Nhập mật khẩu đăng nhập" />*@
                        <span asp-validation-for="passStr" class="d-block invalid-feedback"></span>
                        <!--end::Input-->
                    </div>

                    <div class="fv-row mb-10">
                        <div class="d-flex align-items-center justify-content-between mb-2">
                            <div class="form-check form-switch ver_2">
                                <input class="form-check-input" type="checkbox" id="authen_login_rememberPass">
                                <label class="form-check-label text_6" for="authen_login_rememberPass" style="color:#FCFCFD">
                                    @SharedLocalizer["textRememberPass"].Value
                                </label>
                            </div>

                            <a class="text_5 cursor-pointer " href="/authen/ForgotPassword">
                                @SharedLocalizer["textForgotPassword"].Value
                            </a>
                        </div>
                    </div>
                    <!--end::Input group-->
                    <!--begin::Actions-->
                    <div class="text-center">
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger" style="width:100%"></div>
                        <!--begin::Submit button-->
                        <button type="submit" id="kt_sign_in_submit" class="btn btn-lg btn-success ver_2 w-100 mb-5">
                            <span class="indicator-label">@SharedLocalizer["btnLogin"].Value</span>
                            <span class="indicator-progress">
                                Please wait...
                                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                            </span>
                        </button>
                        <!--end::Submit button-->
                        <!--begin::Separator-->
                        <!--end::Google link-->
                    </div>
                    <!--end::Actions-->
                </form>
                <!--end::Form-->
            </div>
            <!--end::Wrapper-->
        </div>
        <!--end::Content-->
    </div>
    <!--end::Authentication - Sign-in-->
</div>